accounts/urls.py
from django.urls import path

from . import views

from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [

    path('signup/',
         views.SignUpView.as_view(),
         name='signup'),

    path('signup_success/',
         views.SignUpSuccessView.as_view(),
         name='signup_success'),



    path('login/',
         
         auth_views.LoginView.as_view(template_name='login.html'),
         name='login'),


    path('logout/',
         auth_views.LogoutView.as_view(template_name='logout.html'),
         name='logout'),
]

taskapp/urls.py
# Djangoの管理サイトを利用するためのもの
from django.contrib import admin
# urlとview関数を紐づけ(ルーティング)するためのもの
from django.urls import path
# 必要最低限の機能を保有したクラスビューを利用するためのもの
from django.views.generic.base import TemplateView

from django.views.generic.detail import DetailView
# viewsをインポートする
from . import views


# app名の指定
app_name = 'taskapp'

# 紐づけ
urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.IndexView.as_view(), name = 'index'),

    path('properties/', views.PropertiesView.as_view(), name = 'properties'),

    path('property-details/', views.PropertyView.as_view(), name = 'property-details'),

    path('contact/', views.ContactView.as_view(), name = 'contact'),

    path('test/', views.TestView.as_view(), name = 'test'),

    # path('comment/create/<int:pk>/', views.CommentView.as_view(), name='comment_create'),
]

taskproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('taskapp.urls')),

    path('', include('accounts.urls')),
]

accounts/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    
    pass
# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm

from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        # 連携するUserモデルを設定
        model = CustomUser
        # フォームで使用するフィールドを設定
        # ユーザー名、メールアドレス、パスワード、パスワード（確認用）
        fields = ('username', 'email', 'password1', 'password2')

accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView, TemplateView
from .forms import CustomUserCreationForm
from django.urls import reverse_lazy

class SignUpView(CreateView):

    form_class = CustomUserCreationForm

    template_name = "signup.html"

    success_url = reverse_lazy('accounts:signup_success')

    def form_valid(self, form):

        user = form.save()
        self.object = user

        return super().form_valid(form)
    
class SignUpSuccessView(TemplateView):

    template_name = "signup_success.html"

# Create your views here.

accounts/templates/login.html
{% load static %}
<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Log in</title>

    <link rel="icon" type="image/png" href={% static 'images/patapon.png' %} />

    

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href={% static "css/signin.css" %} rel="stylesheet">
  </head>
  <body class="text-center">
    <main class="form-signin">
      <!-- ユーザー名とパスワードが一致しない場合のメッセージ -->
      {% if form.errors %}
        <p style="color: red">ユーザー名とパスワードが一致しません。</p>
      {% endif %}
      <!-- ログインフォームの配置 -->
      <form method="post">
        {% csrf_token %}

      <img class="mb-4" src={% static "images/mati.jpg" %} alt="" width="200" height="150">
      <h1 class="h3 mb-3 fw-normal">Please sign in</h1>
      
      <label for="Username" class="visually-hidden">
        User name</label>

      <input type="text"
             name="username"
             id="id_username"
             maxlength="150"
             autocapitalize="none"
             autocomplete="username"
             class="form-control"
             placeholder="ユーザ名"
             required autofocus>
      
      <label for="Password" class="visually-hidden">
        Password</label>


        <input type="password"
        name="password"
        id="id_password"
        maxlength="150"
        autocomplete="current-password"
        class="form-control"
        placeholder="パスワード"
        required autofocus>

      
          <input class="w-100 btn btn-lg btn-primary" type="submit" value="ログイン">
      <br><br>
      {% comment %} <p><a href="{% url 'password_reset' %}">パスワードを忘れましたか？</a></p> {% endcomment %}

      <input type="hidden"
             name="next"
             value="{% url 'taskapp:index' %}">
      </form>
    </main>


    
  </body>
</html>

accounts/templates/logout.html
{% extends 'base.html' %}
{% block title %}Log out{% endblock %}

    {% block contents %}

    <div class="container">

        <div class="row">

            <div class="col offset-4 py-4">

            <h3>ログアウトしました</h3>

            <p><a href="{% url 'taskapp:index' %}">Homeページへ</a><p>
    {% endblock %}

accounts/templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign up{% endblock %}

    {% block contents %}

    <hr>
    <div class="container">

        <div class="row">

            <div class="col offset-2">
                <h3>サインアップ</h3>

                <form method = "post">
                    {% csrf_token %}

                    {% for field in form %}
                    <p>

                        {{ field.label_tag }}<br>

                        {{ field }}

                        {% if field.help_text %}
                            <small style="color: grey">{{ field.help_text }}</small>
                        {% endif %}

                        {% for error in field.errors %}
                            <p style="color: red">{{ error }}</p>
                        {% endfor %}
                    </p>
                    {% endfor %}
                    <p style="color: red">
                        ※メールアドレスはパスワードをリセットする際に必要になりますので、登録をお願いします。
                    </p>

                    <input type="submit" value="sign up">
                </form>

                <br>
                <p><a href="{% url 'taskapp:index' %}">
                    登録をやめてトップページに戻る</a>
                </p>
            </div>
        </div>
    </div>
    {% endblock %}

accounts/templates/signup_success.html
{% extends 'base.html' %}

{% block title %}Registration Complete{% endblock %}

{% block contents %}

<div class="container">

    <div class="row">

        <div class="col offset-4 py-4">
            <h3>登録が完了しました</h3>

            <!-- ログインページのリンクテキスト -->
            <p><a href="{% url 'accounts:login' %}">ログインはこちら</a><p>
        </div>
    </div>
</div>
{% endblock %}